---
- name: Automatizar configuraciones en los servidores
  hosts: servers
  become: yes
  tasks:

    - name: Actualizar los paquetes del sistema
      apt:
        update_cache: yes
        upgrade: yes

    - name: Crear usuario 'itla'
      user:
        name: itla
        password: "{{ 'itla' | password_hash('sha512') }}"
        shell: /bin/bash
        state: present

    - name: Crear carpeta /home/ansible/app
      file:
        path: /home/ansible/app
        state: directory
        owner: ansible
        group: ansible
        mode: '0755'

    - name: Crear archivo hola.txt dentro de /home/ansible/app
      copy:
        dest: /home/ansible/app/hola.txt
        content: "Hola Mundo desde Ansible en {{ inventory_hostname }}\n"

    - name: Instalar paquetes cowsay y htop
      apt:
        name:
          - cowsay
          - htop
        state: present
        update_cache: yes
